package models;

public enum Operations {

    // Registry 
    NEW_USER_REQUEST,
    AUTHENTICATION_REQUEST, 
    AUTHORIZATION_REQUEST,
    LOGOUT_REQUEST, 
    DELETE_USER_REQUEST,

    // Channel
    NEW_CHANNEL_REQUEST,
    LIST_CHANNELS_REQUEST,
    JOIN_CHANNEL_REQUEST,
    LIST_REQUESTS_REQUEST,
    RESOLVE_REQUEST_REQUEST,

    // DATA
    SHARE_DATA_REQUEST,
    GET_DATA_REQUEST
}